# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'iMovies2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMovies2
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.0'
  pod "youtube-ios-player-helper", "~> 0.1.4"
end

target 'iMovies2Tests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMovies2
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.0'
  pod "youtube-ios-player-helper", "~> 0.1.4"
end
